/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rentmotorbike.incomestat_by_monrth.views;

import com.rentmotorbike.incomestat_by_monrth.dao.BillDAO;
import com.rentmotorbike.incomestat_by_monrth.models.Bill;
import com.rentmotorbike.incomestat_by_monrth.models.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.ArrayList;

/**
 *
 * @author Hạ Quang
 */
public class BillDetailFrm extends javax.swing.JFrame {
    private User user ;
    /**
     * Creates new form BillDetailFrm
     * @param time
     * @param user
     */
    public BillDetailFrm(String time, User user){
        super("List Bill");
        this.user= user;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocation(400,170);
        initComponents();
        lblmonth.setText("Time: "+time);

        ArrayList<Bill> push = new BillDAO().getBillByMonth(time);
        String[][] value = new String[push.size()][8];
        String[] columnNames = {"ID", "Name","RentDay","ReturnDay","price","deposit","Into Money","Total Amount"};
        NumberFormat nf = NumberFormat.getNumberInstance();
        nf.setGroupingUsed(true);
        for (int i = 0; i < push.size(); i++) {
            value[i][0] = String.valueOf(push.get(i).getID());
            value[i][1] = push.get(i).getBooking().getClient().getFullname();
            value[i][2] = String.valueOf(push.get(i).getBooking().getRentDay());
            value[i][3] = String.valueOf(push.get(i).getPaymentDay());
            float price = (float) Math.ceil(Double.parseDouble(String.valueOf(push.get(i).getBooking().getRentedmotorbikes().get(0).getPrice())));
//            System.out.println(push.get(i).getBooking().getRentedmotorbikes().size());
            value[i][4] = nf.format(price);
            float deposit = (float) Math.ceil(Double.parseDouble(String.valueOf(push.get(i).getBooking().getDeposits().get(0).getValue())));
            value[i][5] = nf.format(deposit);
            float intomoney = (float) Math.ceil(Double.parseDouble(String.valueOf(push.get(i).getBooking().getIntoMoney())));
            value[i][6] = nf.format(intomoney);
            float amount = (float) Math.ceil(Double.parseDouble(String.valueOf(push.get(i).getBooking().getTotal())));
            value[i][7] = nf.format(amount);
        }
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblbill.setModel(tableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmonth = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbill = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        returnPreStep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("list bill");

        lblmonth.setText("Month");

        tblbill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "name", "rentday", "returnday ", "price", "deposit", "Into money", "total amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblbill);
        if (tblbill.getColumnModel().getColumnCount() > 0) {
            tblbill.getColumnModel().getColumn(0).setResizable(false);
            tblbill.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        btnBack.setBackground(new java.awt.Color(0, 204, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        returnPreStep.setText("<=");
        returnPreStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnPreStepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(returnPreStep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblmonth)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(returnPreStep))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        (new ManagerHomeFrm(user)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void returnPreStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnPreStepActionPerformed
        // TODO add your handling code here:
        (new IncomeStatFrm(user)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnPreStepActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmonth;
    private javax.swing.JButton returnPreStep;
    private javax.swing.JTable tblbill;
    // End of variables declaration//GEN-END:variables
}
